# Ansible Inventory
# Production servers

[webservers]
# Add your EC2 IP here after terraform apply
# Example: 3.6.39.123 ansible_user=ubuntu

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_rsa